import { createCipheriv, createDecipheriv, randomBytes } from "node:crypto";
import {
  AES256GCMConfig,
  CryptoDecryptInput,
  CryptoEncryptInput,
  CryptoEncryptionResult,
} from "./crypto.types";

export class AES256GCMCrypto {
  constructor(private readonly config: AES256GCMConfig) {}

  encrypt(input: CryptoEncryptInput): CryptoEncryptionResult {
    const iv = randomBytes(this.config.ivLength); //// generate a random IV value.

    //// create a cipher object. This object is used to encrypt the data
    const cipher = createCipheriv(this.config.algorithm, input.key, iv);

    /// encrypt the plaintext and convert it into ciphertext
    const ciphertext = Buffer.concat([
      cipher.update(input.plaintext, "utf8"), /// convert the plaintext string into bytes and encrypt it
      cipher.final(), /// Finish the encryption operation
    ]);

    const authTag = cipher.getAuthTag(); /// Get the authentication tag generated by GCM

    return {
      iv,
      ciphertext,
      authTag,
    };
  }

  decrypt(input: CryptoDecryptInput): string {
    const decipher = createDecipheriv(
      this.config.algorithm,
      input.key,
      input.iv,
    );

    decipher.setAuthTag(input.authTag); //// provide the authentication tag so GCM can verify the ciphertext

    const plaintext = Buffer.concat([
      decipher.update(input.ciphertext), /// decrypt the ciphertext
      decipher.final(), //// finish the decryption and verify the authentication tag
    ]);

    return plaintext.toString("utf8"); //// Convert the decrypted bytes back into a UTF-8 plaintext string
  }
}
